/* eslint-disable max-len */
import { ImageSourcePropType } from 'react-native';

export type LanguageCode = '' | 'und' | 'eng' | 'rus' | 'ita' | 'tur' | 'epo' | 'ber' | 'deu' | 'kab' | 'fra' | 'por' | 'spa' | 'hun' | 'jpn' | 'heb' | 'ukr' | 'nld' | 'fin' | 'pol' | 'lit' | 'mkd' | 'cmn' | 'mar' | 'ces' | 'dan' | 'swe' | 'tok' | 'srp' | 'lat' | 'ara' | 'ell' | 'ron' | 'ina' | 'pes' | 'bul' | 'swc' | 'tlh' | 'hau' | 'lfn' | 'vie' | 'tgl' | 'nds' | 'slk' | 'nob' | 'ind' | 'jbo' | 'hin' | 'nnb' | 'tat' | 'isl' | 'bel' | 'ckb' | 'kor' | 'yid' | 'ido' | 'kmr' | 'cat' | 'uig' | 'ile' | 'bre' | 'zsm' | 'oss' | 'tuk' | 'yue' | 'eus' | 'kat' | 'oci' | 'gos' | 'aze' | 'ben' | 'hrv' | 'kzj' | 'run' | 'tha' | 'hye' | 'vol' | 'lin' | 'wuu' | 'glg' | 'swh' | 'mhr' | 'afr' | 'kaz' | 'avk' | 'cor' | 'tig' | 'rhg' | 'knc' | 'est' | 'asm' | 'grn' | 'zgh' | 'lvs' | 'dtp' | 'gle' | 'frr' | 'mon' | 'shi' | 'cbk' | 'sqi' | 'ilo' | 'urd' | 'arq' | 'ota' | 'gcf' | 'nus' | 'kha' | 'war' | 'swg' | 'lzh' | 'lij' | 'sat' | 'zza' | 'chv' | 'cym' | 'zlm' | 'nno' | 'ceb' | 'hsb' | 'khm' | 'pam' | 'unknown' | 'pcd' | 'orv' | 'lad' | 'grc' | 'slv' | 'arz' | 'hrx' | 'dsb' | 'gla' | 'sdh' | 'uzb' | 'prg' | 'jav' | 'sah' | 'csb' | 'guc' | 'bua' | 'ltz' | 'mal' | 'rom' | 'xal' | 'pms' | 'nst' | 'hoc' | 'bos' | 'xmf' | 'mus' | 'thv' | 'tpw' | 'mya' | 'ckt' | 'fkv' | 'fry' | 'tam' | 'gsw' | 'max' | 'que' | 'nov' | 'fao' | 'mri' | 'ori' | 'ang' | 'cha' | 'tzl' | 'kir' | 'crh' | 'mfa' | 'ain' | 'ast' | 'tel' | 'got' | 'bzt' | 'xho' | 'awa' | 'amh' | 'shy' | 'bak' | 'rif' | 'bar' | 'lao' | 'mlt' | 'fro' | 'krc' | 'nah' | 'sme' | 'tmr' | 'pan' | 'kan' | 'srn' | 'krl' | 'haw' | 'vec' | 'sux' | 'npi' | 'guj' | 'nog' | 'san' | 'qya' | 'egl' | 'bal' | 'ldn' | 'hbo' | 'afb' | 'bjn' | 'enm' | 'cho' | 'kum' | 'min' | 'som' | 'rue' | 'evn' | 'wol' | 'zul' | 'mik' | 'tir' | 'arg' | 'apc' | 'stq' | 'hat' | 'shs' | 'pap' | 'tpi' | 'sjn' | 'nav' | 'sco' | 'lld' | 'cmo' | 'smo' | 'mrj' | 'mww' | 'ksh' | 'afh' | 'kal' | 'tyv' | 'bvy' | 'moh' | 'kbd' | 'lzz' | 'ary' | 'udm' | 'myv' | 'skr' | 'crs' | 'tly' | 'ext' | 'tgk' | 'iba' | 'iii' | 'mlg' | 'mgm' | 'pus' | 'lut' | 'tet' | 'ppl' | 'sma' | 'dws' | 'bod' | 'bfz' | 'pdc' | 'pag' | 'bho' | 'tts' | 'hak' | 'sin' | 'wln' | 'chn' | 'bom' | 'ike' | 'acm' | 'kas' | 'yor' | 'sgs' | 'kpv' | 'lim' | 'hil' | 'sna' | 'ngu' | 'fij' | 'koi' | 'kjh' | 'ryu' | 'tsn' | 'drt' | 'div' | 'nch' | 'glv' | 'gag' | 'gbm' | 'cycl' | 'pnb' | 'scn' | 'niu' | 'fuv' | 'oji' | 'hif' | 'ibo' | 'pau' | 'jam' | 'liv' | 'rap' | 'fur' | 'ltg' | 'ady' | 'frm' | 'dng' | 'abk' | 'igs' | 'cay' | 'sun' | 'tah' | 'umb' | 'chr' | 'lmo' | 'akl' | 'aln' | 'mvv' | 'che' | 'bis' | 'kin' | 'ood' | 'mah' | 'ewe' | 'nya' | 'lkt' | 'roh' | 'ton' | 'aoz' | 'kek' | 'cos' | 'ava' | 'mwl' | 'oar' | 'lou' | 'izh' | 'non' | 'osp' | 'klj' | 'inh' | 'dar' | 'ngt' | 'mic' | 'cjy' | 'kaa' | 'new' | 'jpa' | 'vro' | 'srd' | 'toi' | 'nan' | 'lez' | 'phn' | 'qxq' | 'gil' | 'nlv' | 'tvl' | 'lbe' | 'vep' | 'bam' | 'ofs' | 'alt' | 'xqa' | 'tkl' | 'zea' | 'emx' | 'abq' | 'brx' | 'nau' | 'yua' | 'laa' | 'szl' | 'kam' | 'mdf' | 'mnw' | 'jdt' | 'ajp' | 'sag' | 'mai' | 'chg' | 'otk' | 'cpi' | 'mad' | 'fuc' | 'quc' | 'ban' | 'aii' | 'diq' | 'kiu' | 'snd' | 'mfe' | 'bcl' | 'pal' | 'tmw' | 'kxi' | 'gom' | 'hsn' | 'hnj' | 'crk' | 'gaa' | 'gan' | 'ayl' | 'mnr' | 'syc' | 'mni' | 'tso' | 'osx' | 'pfl' | 'hdn' | 'lug' | 'mnc' | 'aym' | 'sot' | 'nys' | 'pli' | 'cyo' | 'rel' | 'ssw' | 'hax' | 'urh';

export type Language = {
  name: string;
  code: LanguageCode;
  icon: ImageSourcePropType;
};

export const languages: Language[] = [
  { code: 'eng', name: 'English', icon: require('@assets/flags/eng.png') },
  { code: 'rus', name: 'Russian', icon: require('@assets/flags/rus.png') },
  { code: 'ita', name: 'Italian', icon: require('@assets/flags/ita.png') },
  { code: 'tur', name: 'Turkish', icon: require('@assets/flags/tur.png') },
  { code: 'epo', name: 'Esperanto', icon: require('@assets/flags/epo.png') },
  { code: 'ber', name: 'Berber', icon: require('@assets/flags/ber.png') },
  { code: 'deu', name: 'German', icon: require('@assets/flags/deu.png') },
  { code: 'kab', name: 'Kabyle', icon: require('@assets/flags/kab.png') },
  { code: 'fra', name: 'French', icon: require('@assets/flags/fra.png') },
  { code: 'por', name: 'Portuguese', icon: require('@assets/flags/por.png') },
  { code: 'spa', name: 'Spanish', icon: require('@assets/flags/spa.png') },
  { code: 'hun', name: 'Hungarian', icon: require('@assets/flags/hun.png') },
  { code: 'jpn', name: 'Japanese', icon: require('@assets/flags/jpn.png') },
  { code: 'heb', name: 'Hebrew', icon: require('@assets/flags/heb.png') },
  { code: 'ukr', name: 'Ukrainian', icon: require('@assets/flags/ukr.png') },
  { code: 'nld', name: 'Dutch', icon: require('@assets/flags/nld.png') },
  { code: 'fin', name: 'Finnish', icon: require('@assets/flags/fin.png') },
  { code: 'pol', name: 'Polish', icon: require('@assets/flags/pol.png') },
  { code: 'lit', name: 'Lithuanian', icon: require('@assets/flags/lit.png') },
  { code: 'mkd', name: 'Macedonian', icon: require('@assets/flags/mkd.png') },
  { code: 'cmn', name: 'Mandarin Chinese', icon: require('@assets/flags/cmn.png') },
  { code: 'mar', name: 'Marathi', icon: require('@assets/flags/mar.png') },
  { code: 'ces', name: 'Czech', icon: require('@assets/flags/ces.png') },
  { code: 'dan', name: 'Danish', icon: require('@assets/flags/dan.png') },
  { code: 'swe', name: 'Swedish', icon: require('@assets/flags/swe.png') },
  { code: 'tok', name: 'Toki Pona', icon: require('@assets/flags/tok.png') },
  { code: 'srp', name: 'Serbian', icon: require('@assets/flags/srp.png') },
  { code: 'lat', name: 'Latin', icon: require('@assets/flags/lat.png') },
  { code: 'ara', name: 'Arabic', icon: require('@assets/flags/ara.png') },
  { code: 'ell', name: 'Greek', icon: require('@assets/flags/ell.png') },
  { code: 'ron', name: 'Romanian', icon: require('@assets/flags/ron.png') },
  { code: 'ina', name: 'Interlingua', icon: require('@assets/flags/ina.png') },
  { code: 'pes', name: 'Persian', icon: require('@assets/flags/pes.png') },
  { code: 'bul', name: 'Bulgarian', icon: require('@assets/flags/bul.png') },
  { code: 'swc', name: 'Congo Swahili', icon: require('@assets/flags/swc.png') },
  { code: 'tlh', name: 'Klingon', icon: require('@assets/flags/tlh.png') },
  { code: 'hau', name: 'Hausa', icon: require('@assets/flags/hau.png') },
  { code: 'lfn', name: 'Lingua Franca Nova', icon: require('@assets/flags/lfn.png') },
  { code: 'vie', name: 'Vietnamese', icon: require('@assets/flags/vie.png') },
  { code: 'tgl', name: 'Tagalog', icon: require('@assets/flags/tgl.png') },
  { code: 'nds', name: 'Low German (Low Saxon)', icon: require('@assets/flags/nds.png') },
  { code: 'slk', name: 'Slovak', icon: require('@assets/flags/slk.png') },
  { code: 'nob', name: 'Norwegian Bokmål', icon: require('@assets/flags/nob.png') },
  { code: 'ind', name: 'Indonesian', icon: require('@assets/flags/ind.png') },
  { code: 'jbo', name: 'Lojban', icon: require('@assets/flags/jbo.png') },
  { code: 'hin', name: 'Hindi', icon: require('@assets/flags/hin.png') },
  { code: 'nnb', name: 'Nande', icon: require('@assets/flags/nnb.png') },
  { code: 'tat', name: 'Tatar', icon: require('@assets/flags/tat.png') },
  { code: 'isl', name: 'Icelandic', icon: require('@assets/flags/isl.png') },
  { code: 'bel', name: 'Belarusian', icon: require('@assets/flags/bel.png') },
  { code: 'ckb', name: 'Central Kurdish (Soranî)', icon: require('@assets/flags/ckb.png') },
  { code: 'kor', name: 'Korean', icon: require('@assets/flags/kor.png') },
  { code: 'yid', name: 'Yiddish', icon: require('@assets/flags/yid.png') },
  { code: 'ido', name: 'Ido', icon: require('@assets/flags/ido.png') },
  { code: 'kmr', name: 'Northern Kurdish (Kurmancî)', icon: require('@assets/flags/kmr.png') },
  { code: 'cat', name: 'Catalan', icon: require('@assets/flags/cat.png') },
  { code: 'uig', name: 'Uyghur', icon: require('@assets/flags/uig.png') },
  { code: 'ile', name: 'Interlingue', icon: require('@assets/flags/ile.png') },
  { code: 'bre', name: 'Breton', icon: require('@assets/flags/bre.png') },
  { code: 'zsm', name: 'Malay', icon: require('@assets/flags/zsm.png') },
  { code: 'oss', name: 'Ossetian', icon: require('@assets/flags/oss.png') },
  { code: 'tuk', name: 'Turkmen', icon: require('@assets/flags/tuk.png') },
  { code: 'yue', name: 'Cantonese', icon: require('@assets/flags/yue.png') },
  { code: 'eus', name: 'Basque', icon: require('@assets/flags/eus.png') },
  { code: 'kat', name: 'Georgian', icon: require('@assets/flags/kat.png') },
  { code: 'oci', name: 'Occitan', icon: require('@assets/flags/oci.png') },
  { code: 'gos', name: 'Gronings', icon: require('@assets/flags/gos.png') },
  { code: 'aze', name: 'Azerbaijani', icon: require('@assets/flags/aze.png') },
  { code: 'ben', name: 'Bengali', icon: require('@assets/flags/ben.png') },
  { code: 'hrv', name: 'Croatian', icon: require('@assets/flags/hrv.png') },
  { code: 'kzj', name: 'Coastal Kadazan', icon: require('@assets/flags/kzj.png') },
  { code: 'run', name: 'Kirundi', icon: require('@assets/flags/run.png') },
  { code: 'tha', name: 'Thai', icon: require('@assets/flags/tha.png') },
  { code: 'hye', name: 'Armenian', icon: require('@assets/flags/hye.png') },
  { code: 'vol', name: 'Volapük', icon: require('@assets/flags/vol.png') },
  { code: 'lin', name: 'Lingala', icon: require('@assets/flags/lin.png') },
  { code: 'wuu', name: 'Shanghainese', icon: require('@assets/flags/wuu.png') },
  { code: 'glg', name: 'Galician', icon: require('@assets/flags/glg.png') },
  { code: 'swh', name: 'Swahili', icon: require('@assets/flags/swh.png') },
  { code: 'mhr', name: 'Meadow Mari', icon: require('@assets/flags/mhr.png') },
  { code: 'afr', name: 'Afrikaans', icon: require('@assets/flags/afr.png') },
  { code: 'kaz', name: 'Kazakh', icon: require('@assets/flags/kaz.png') },
  { code: 'avk', name: 'Kotava', icon: require('@assets/flags/avk.png') },
  { code: 'cor', name: 'Cornish', icon: require('@assets/flags/cor.png') },
  { code: 'tig', name: 'Tigre', icon: require('@assets/flags/tig.png') },
  { code: 'rhg', name: 'Rohingya', icon: require('@assets/flags/rhg.png') },
  { code: 'knc', name: 'Central Kanuri', icon: require('@assets/flags/knc.png') },
  { code: 'est', name: 'Estonian', icon: require('@assets/flags/est.png') },
  { code: 'asm', name: 'Assamese', icon: require('@assets/flags/asm.png') },
  { code: 'grn', name: 'Guarani', icon: require('@assets/flags/grn.png') },
  { code: 'zgh', name: 'Standard Moroccan Tamazight', icon: require('@assets/flags/zgh.png') },
  { code: 'lvs', name: 'Latvian', icon: require('@assets/flags/lvs.png') },
  { code: 'dtp', name: 'Central Dusun', icon: require('@assets/flags/dtp.png') },
  { code: 'gle', name: 'Irish', icon: require('@assets/flags/gle.png') },
  { code: 'frr', name: 'North Frisian', icon: require('@assets/flags/frr.png') },
  { code: 'mon', name: 'Mongolian', icon: require('@assets/flags/mon.png') },
  { code: 'shi', name: 'Tashelhit', icon: require('@assets/flags/shi.png') },
  { code: 'cbk', name: 'Chavacano', icon: require('@assets/flags/cbk.png') },
  { code: 'sqi', name: 'Albanian', icon: require('@assets/flags/sqi.png') },
  { code: 'ilo', name: 'Ilocano', icon: require('@assets/flags/ilo.png') },
  { code: 'urd', name: 'Urdu', icon: require('@assets/flags/urd.png') },
  { code: 'arq', name: 'Algerian Arabic', icon: require('@assets/flags/arq.png') },
  { code: 'ota', name: 'Ottoman Turkish', icon: require('@assets/flags/ota.png') },
  { code: 'gcf', name: 'Guadeloupean Creole French', icon: require('@assets/flags/gcf.png') },
  { code: 'nus', name: 'Nuer', icon: require('@assets/flags/nus.png') },
  { code: 'kha', name: 'Khasi', icon: require('@assets/flags/kha.png') },
  { code: 'war', name: 'Waray', icon: require('@assets/flags/war.png') },
  { code: 'swg', name: 'Swabian', icon: require('@assets/flags/swg.png') },
  { code: 'lzh', name: 'Literary Chinese', icon: require('@assets/flags/lzh.png') },
  { code: 'lij', name: 'Ligurian', icon: require('@assets/flags/lij.png') },
  { code: 'sat', name: 'Santali', icon: require('@assets/flags/sat.png') },
  { code: 'zza', name: 'Zaza', icon: require('@assets/flags/zza.png') },
  { code: 'chv', name: 'Chuvash', icon: require('@assets/flags/chv.png') },
  { code: 'cym', name: 'Welsh', icon: require('@assets/flags/cym.png') },
  { code: 'zlm', name: 'Malay (Vernacular)', icon: require('@assets/flags/zlm.png') },
  { code: 'nno', name: 'Norwegian Nynorsk', icon: require('@assets/flags/nno.png') },
  { code: 'ceb', name: 'Cebuano', icon: require('@assets/flags/ceb.png') },
  { code: 'hsb', name: 'Upper Sorbian', icon: require('@assets/flags/hsb.png') },
  { code: 'khm', name: 'Khmer', icon: require('@assets/flags/khm.png') },
  { code: 'pam', name: 'Kapampangan', icon: require('@assets/flags/pam.png') },
  { code: 'unknown', name: 'unknown', icon: require('@assets/flags/unknown.png') },
  { code: 'pcd', name: 'Picard', icon: require('@assets/flags/pcd.png') },
  { code: 'orv', name: 'Old East Slavic', icon: require('@assets/flags/orv.png') },
  { code: 'lad', name: 'Ladino', icon: require('@assets/flags/lad.png') },
  { code: 'grc', name: 'Ancient Greek', icon: require('@assets/flags/grc.png') },
  { code: 'slv', name: 'Slovenian', icon: require('@assets/flags/slv.png') },
  { code: 'arz', name: 'Egyptian Arabic', icon: require('@assets/flags/arz.png') },
  { code: 'hrx', name: 'Hunsrik', icon: require('@assets/flags/hrx.png') },
  { code: 'dsb', name: 'Lower Sorbian', icon: require('@assets/flags/dsb.png') },
  { code: 'gla', name: 'Scottish Gaelic', icon: require('@assets/flags/gla.png') },
  { code: 'sdh', name: 'Southern Kurdish', icon: require('@assets/flags/sdh.png') },
  { code: 'uzb', name: 'Uzbek', icon: require('@assets/flags/uzb.png') },
  { code: 'prg', name: 'Old Prussian', icon: require('@assets/flags/prg.png') },
  { code: 'jav', name: 'Javanese', icon: require('@assets/flags/jav.png') },
  { code: 'sah', name: 'Yakut', icon: require('@assets/flags/sah.png') },
  { code: 'csb', name: 'Kashubian', icon: require('@assets/flags/csb.png') },
  { code: 'guc', name: 'Wayuu', icon: require('@assets/flags/guc.png') },
  { code: 'bua', name: 'Buryat', icon: require('@assets/flags/bua.png') },
  { code: 'ltz', name: 'Luxembourgish', icon: require('@assets/flags/ltz.png') },
  { code: 'mal', name: 'Malayalam', icon: require('@assets/flags/mal.png') },
  { code: 'rom', name: 'Romani', icon: require('@assets/flags/rom.png') },
  { code: 'xal', name: 'Kalmyk', icon: require('@assets/flags/xal.png') },
  { code: 'pms', name: 'Piedmontese', icon: require('@assets/flags/pms.png') },
  { code: 'nst', name: 'Naga (Tangshang)', icon: require('@assets/flags/nst.png') },
  { code: 'hoc', name: 'Ho', icon: require('@assets/flags/hoc.png') },
  { code: 'bos', name: 'Bosnian', icon: require('@assets/flags/bos.png') },
  { code: 'xmf', name: 'Mingrelian', icon: require('@assets/flags/xmf.png') },
  { code: 'mus', name: 'Muskogee (Creek)', icon: require('@assets/flags/mus.png') },
  { code: 'thv', name: 'Tahaggart Tamahaq', icon: require('@assets/flags/thv.png') },
  { code: 'tpw', name: 'Old Tupi', icon: require('@assets/flags/tpw.png') },
  { code: 'mya', name: 'Burmese', icon: require('@assets/flags/mya.png') },
  { code: 'ckt', name: 'Chukchi', icon: require('@assets/flags/ckt.png') },
  { code: 'fkv', name: 'Kven Finnish', icon: require('@assets/flags/fkv.png') },
  { code: 'fry', name: 'Frisian', icon: require('@assets/flags/fry.png') },
  { code: 'tam', name: 'Tamil', icon: require('@assets/flags/tam.png') },
  { code: 'gsw', name: 'Swiss German', icon: require('@assets/flags/gsw.png') },
  { code: 'max', name: 'North Moluccan Malay', icon: require('@assets/flags/max.png') },
  { code: 'que', name: 'Quechua', icon: require('@assets/flags/que.png') },
  { code: 'nov', name: 'Novial', icon: require('@assets/flags/nov.png') },
  { code: 'fao', name: 'Faroese', icon: require('@assets/flags/fao.png') },
  { code: 'mri', name: 'Maori', icon: require('@assets/flags/mri.png') },
  { code: 'ori', name: 'Odia (Oriya)', icon: require('@assets/flags/ori.png') },
  { code: 'ang', name: 'Old English', icon: require('@assets/flags/ang.png') },
  { code: 'cha', name: 'Chamorro', icon: require('@assets/flags/cha.png') },
  { code: 'tzl', name: 'Talossan', icon: require('@assets/flags/tzl.png') },
  { code: 'kir', name: 'Kyrgyz', icon: require('@assets/flags/kir.png') },
  { code: 'crh', name: 'Crimean Tatar', icon: require('@assets/flags/crh.png') },
  { code: 'mfa', name: 'Kelantan-Pattani Malay', icon: require('@assets/flags/mfa.png') },
  { code: 'ain', name: 'Ainu', icon: require('@assets/flags/ain.png') },
  { code: 'ast', name: 'Asturian', icon: require('@assets/flags/ast.png') },
  { code: 'tel', name: 'Telugu', icon: require('@assets/flags/tel.png') },
  { code: 'got', name: 'Gothic', icon: require('@assets/flags/got.png') },
  { code: 'bzt', name: 'Brithenig', icon: require('@assets/flags/bzt.png') },
  { code: 'xho', name: 'Xhosa', icon: require('@assets/flags/xho.png') },
  { code: 'awa', name: 'Awadhi', icon: require('@assets/flags/awa.png') },
  { code: 'amh', name: 'Amharic', icon: require('@assets/flags/amh.png') },
  { code: 'shy', name: 'Tachawit', icon: require('@assets/flags/shy.png') },
  { code: 'bak', name: 'Bashkir', icon: require('@assets/flags/bak.png') },
  { code: 'rif', name: 'Tarifit', icon: require('@assets/flags/rif.png') },
  { code: 'bar', name: 'Bavarian', icon: require('@assets/flags/bar.png') },
  { code: 'lao', name: 'Lao', icon: require('@assets/flags/lao.png') },
  { code: 'mlt', name: 'Maltese', icon: require('@assets/flags/mlt.png') },
  { code: 'fro', name: 'Old French', icon: require('@assets/flags/fro.png') },
  { code: 'krc', name: 'Karachay-Balkar', icon: require('@assets/flags/krc.png') },
  { code: 'nah', name: 'Nahuatl', icon: require('@assets/flags/nah.png') },
  { code: 'sme', name: 'Northern Sami', icon: require('@assets/flags/sme.png') },
  { code: 'tmr', name: 'Jewish Babylonian Aramaic', icon: require('@assets/flags/tmr.png') },
  { code: 'pan', name: 'Punjabi (Eastern)', icon: require('@assets/flags/pan.png') },
  { code: 'kan', name: 'Kannada', icon: require('@assets/flags/kan.png') },
  { code: 'srn', name: 'Sranan Tongo', icon: require('@assets/flags/srn.png') },
  { code: 'krl', name: 'Karelian', icon: require('@assets/flags/krl.png') },
  { code: 'haw', name: 'Hawaiian', icon: require('@assets/flags/haw.png') },
  { code: 'vec', name: 'Venetian', icon: require('@assets/flags/vec.png') },
  { code: 'sux', name: 'Sumerian', icon: require('@assets/flags/sux.png') },
  { code: 'npi', name: 'Nepali', icon: require('@assets/flags/npi.png') },
  { code: 'guj', name: 'Gujarati', icon: require('@assets/flags/guj.png') },
  { code: 'nog', name: 'Nogai', icon: require('@assets/flags/nog.png') },
  { code: 'san', name: 'Sanskrit', icon: require('@assets/flags/san.png') },
  { code: 'qya', name: 'Quenya', icon: require('@assets/flags/qya.png') },
  { code: 'egl', name: 'Emilian', icon: require('@assets/flags/egl.png') },
  { code: 'bal', name: 'Baluchi', icon: require('@assets/flags/bal.png') },
  { code: 'ldn', name: 'Láadan', icon: require('@assets/flags/ldn.png') },
  { code: 'hbo', name: 'Ancient Hebrew', icon: require('@assets/flags/hbo.png') },
  { code: 'afb', name: 'Gulf Arabic', icon: require('@assets/flags/afb.png') },
  { code: 'bjn', name: 'Banjar', icon: require('@assets/flags/bjn.png') },
  { code: 'enm', name: 'Middle English', icon: require('@assets/flags/enm.png') },
  { code: 'cho', name: 'Choctaw', icon: require('@assets/flags/cho.png') },
  { code: 'kum', name: 'Kumyk', icon: require('@assets/flags/kum.png') },
  { code: 'min', name: 'Minangkabau', icon: require('@assets/flags/min.png') },
  { code: 'som', name: 'Somali', icon: require('@assets/flags/som.png') },
  { code: 'rue', name: 'Rusyn', icon: require('@assets/flags/rue.png') },
  { code: 'evn', name: 'Evenki', icon: require('@assets/flags/evn.png') },
  { code: 'wol', name: 'Wolof', icon: require('@assets/flags/wol.png') },
  { code: 'zul', name: 'Zulu', icon: require('@assets/flags/zul.png') },
  { code: 'mik', name: 'Hitchiti', icon: require('@assets/flags/mik.png') },
  { code: 'tir', name: 'Tigrinya', icon: require('@assets/flags/tir.png') },
  { code: 'arg', name: 'Aragonese', icon: require('@assets/flags/arg.png') },
  { code: 'apc', name: 'North Levantine Arabic', icon: require('@assets/flags/apc.png') },
  { code: 'stq', name: 'Saterland Frisian', icon: require('@assets/flags/stq.png') },
  { code: 'hat', name: 'Haitian Creole', icon: require('@assets/flags/hat.png') },
  { code: 'shs', name: 'Shuswap', icon: require('@assets/flags/shs.png') },
  { code: 'pap', name: 'Papiamento', icon: require('@assets/flags/pap.png') },
  { code: 'tpi', name: 'Tok Pisin', icon: require('@assets/flags/tpi.png') },
  { code: 'sjn', name: 'Sindarin', icon: require('@assets/flags/sjn.png') },
  { code: 'nav', name: 'Navajo', icon: require('@assets/flags/nav.png') },
  { code: 'sco', name: 'Scots', icon: require('@assets/flags/sco.png') },
  { code: 'lld', name: 'Ladin', icon: require('@assets/flags/lld.png') },
  { code: 'cmo', name: 'Central Mnong', icon: require('@assets/flags/cmo.png') },
  { code: 'smo', name: 'Samoan', icon: require('@assets/flags/smo.png') },
  { code: 'mrj', name: 'Hill Mari', icon: require('@assets/flags/mrj.png') },
  { code: 'mww', name: 'Hmong Daw (White)', icon: require('@assets/flags/mww.png') },
  { code: 'ksh', name: 'Kölsch', icon: require('@assets/flags/ksh.png') },
  { code: 'afh', name: 'Afrihili', icon: require('@assets/flags/afh.png') },
  { code: 'kal', name: 'Greenlandic', icon: require('@assets/flags/kal.png') },
  { code: 'tyv', name: 'Tuvinian', icon: require('@assets/flags/tyv.png') },
  { code: 'bvy', name: 'Baybayanon', icon: require('@assets/flags/bvy.png') },
  { code: 'moh', name: 'Mohawk', icon: require('@assets/flags/moh.png') },
  { code: 'kbd', name: 'Kabardian', icon: require('@assets/flags/kbd.png') },
  { code: 'lzz', name: 'Laz', icon: require('@assets/flags/lzz.png') },
  { code: 'ary', name: 'Moroccan Arabic', icon: require('@assets/flags/ary.png') },
  { code: 'udm', name: 'Udmurt', icon: require('@assets/flags/udm.png') },
  { code: 'myv', name: 'Erzya', icon: require('@assets/flags/myv.png') },
  { code: 'skr', name: 'Saraiki', icon: require('@assets/flags/skr.png') },
  { code: 'crs', name: 'Seychellois Creole', icon: require('@assets/flags/crs.png') },
  { code: 'tly', name: 'Talysh', icon: require('@assets/flags/tly.png') },
  { code: 'ext', name: 'Extremaduran', icon: require('@assets/flags/ext.png') },
  { code: 'tgk', name: 'Tajik', icon: require('@assets/flags/tgk.png') },
  { code: 'iba', name: 'Iban', icon: require('@assets/flags/iba.png') },
  { code: 'iii', name: 'Nuosu', icon: require('@assets/flags/iii.png') },
  { code: 'mlg', name: 'Malagasy', icon: require('@assets/flags/mlg.png') },
  { code: 'mgm', name: 'Mambae', icon: require('@assets/flags/mgm.png') },
  { code: 'pus', name: 'Pashto', icon: require('@assets/flags/pus.png') },
  { code: 'lut', name: 'Lushootseed', icon: require('@assets/flags/lut.png') },
  { code: 'tet', name: 'Tetun', icon: require('@assets/flags/tet.png') },
  { code: 'ppl', name: 'Pipil', icon: require('@assets/flags/ppl.png') },
  { code: 'sma', name: 'Southern Sami', icon: require('@assets/flags/sma.png') },
  { code: 'dws', name: 'Dutton World Speedwords', icon: require('@assets/flags/dws.png') },
  { code: 'bod', name: 'Tibetan', icon: require('@assets/flags/bod.png') },
  { code: 'bfz', name: 'Mahasu Pahari', icon: require('@assets/flags/bfz.png') },
  { code: 'pdc', name: 'Pennsylvania German', icon: require('@assets/flags/pdc.png') },
  { code: 'pag', name: 'Pangasinan', icon: require('@assets/flags/pag.png') },
  { code: 'bho', name: 'Bhojpuri', icon: require('@assets/flags/bho.png') },
  { code: 'tts', name: 'Isan', icon: require('@assets/flags/tts.png') },
  { code: 'hak', name: 'Hakka Chinese', icon: require('@assets/flags/hak.png') },
  { code: 'sin', name: 'Sinhala', icon: require('@assets/flags/sin.png') },
  { code: 'wln', name: 'Walloon', icon: require('@assets/flags/wln.png') },
  { code: 'chn', name: 'Chinook Jargon', icon: require('@assets/flags/chn.png') },
  { code: 'bom', name: 'Berom', icon: require('@assets/flags/bom.png') },
  { code: 'ike', name: 'Inuktitut', icon: require('@assets/flags/ike.png') },
  { code: 'acm', name: 'Iraqi Arabic', icon: require('@assets/flags/acm.png') },
  { code: 'kas', name: 'Kashmiri', icon: require('@assets/flags/kas.png') },
  { code: 'yor', name: 'Yoruba', icon: require('@assets/flags/yor.png') },
  { code: 'sgs', name: 'Samogitian', icon: require('@assets/flags/sgs.png') },
  { code: 'kpv', name: 'Komi-Zyrian', icon: require('@assets/flags/kpv.png') },
  { code: 'lim', name: 'Limburgish', icon: require('@assets/flags/lim.png') },
  { code: 'hil', name: 'Hiligaynon', icon: require('@assets/flags/hil.png') },
  { code: 'sna', name: 'Shona', icon: require('@assets/flags/sna.png') },
  { code: 'ngu', name: 'Guerrero Nahuatl', icon: require('@assets/flags/ngu.png') },
  { code: 'fij', name: 'Fijian', icon: require('@assets/flags/fij.png') },
  { code: 'koi', name: 'Komi-Permyak', icon: require('@assets/flags/koi.png') },
  { code: 'kjh', name: 'Khakas', icon: require('@assets/flags/kjh.png') },
  { code: 'ryu', name: 'Okinawan', icon: require('@assets/flags/ryu.png') },
  { code: 'tsn', name: 'Setswana', icon: require('@assets/flags/tsn.png') },
  { code: 'drt', name: 'Drents', icon: require('@assets/flags/drt.png') },
  { code: 'div', name: 'Dhivehi', icon: require('@assets/flags/div.png') },
  { code: 'nch', name: 'Central Huasteca Nahuatl', icon: require('@assets/flags/nch.png') },
  { code: 'glv', name: 'Manx', icon: require('@assets/flags/glv.png') },
  { code: 'gag', name: 'Gagauz', icon: require('@assets/flags/gag.png') },
  { code: 'gbm', name: 'Garhwali', icon: require('@assets/flags/gbm.png') },
  { code: 'cycl', name: 'CycL', icon: require('@assets/flags/cycl.png') },
  { code: 'pnb', name: 'Punjabi (Western)', icon: require('@assets/flags/pnb.png') },
  { code: 'scn', name: 'Sicilian', icon: require('@assets/flags/scn.png') },
  { code: 'niu', name: 'Niuean', icon: require('@assets/flags/niu.png') },
  { code: 'fuv', name: 'Nigerian Fulfulde', icon: require('@assets/flags/fuv.png') },
  { code: 'oji', name: 'Ojibwe', icon: require('@assets/flags/oji.png') },
  { code: 'hif', name: 'Fiji Hindi', icon: require('@assets/flags/hif.png') },
  { code: 'ibo', name: 'Igbo', icon: require('@assets/flags/ibo.png') },
  { code: 'pau', name: 'Palauan', icon: require('@assets/flags/pau.png') },
  { code: 'jam', name: 'Jamaican Patois', icon: require('@assets/flags/jam.png') },
  { code: 'liv', name: 'Livonian', icon: require('@assets/flags/liv.png') },
  { code: 'rap', name: 'Rapa Nui', icon: require('@assets/flags/rap.png') },
  { code: 'fur', name: 'Friulian', icon: require('@assets/flags/fur.png') },
  { code: 'ltg', name: 'Latgalian', icon: require('@assets/flags/ltg.png') },
  { code: 'ady', name: 'Adyghe', icon: require('@assets/flags/ady.png') },
  { code: 'frm', name: 'Middle French', icon: require('@assets/flags/frm.png') },
  { code: 'dng', name: 'Dungan', icon: require('@assets/flags/dng.png') },
  { code: 'abk', name: 'Abkhaz', icon: require('@assets/flags/abk.png') },
  { code: 'igs', name: 'Interglossa', icon: require('@assets/flags/igs.png') },
  { code: 'cay', name: 'Cayuga', icon: require('@assets/flags/cay.png') },
  { code: 'sun', name: 'Sundanese', icon: require('@assets/flags/sun.png') },
  { code: 'tah', name: 'Tahitian', icon: require('@assets/flags/tah.png') },
  { code: 'umb', name: 'Umbundu', icon: require('@assets/flags/umb.png') },
  { code: 'chr', name: 'Cherokee', icon: require('@assets/flags/chr.png') },
  { code: 'lmo', name: 'Lombard', icon: require('@assets/flags/lmo.png') },
  { code: 'akl', name: 'Aklanon', icon: require('@assets/flags/akl.png') },
  { code: 'aln', name: 'Gheg Albanian', icon: require('@assets/flags/aln.png') },
  { code: 'mvv', name: 'Tagal Murut', icon: require('@assets/flags/mvv.png') },
  { code: 'che', name: 'Chechen', icon: require('@assets/flags/che.png') },
  { code: 'bis', name: 'Bislama', icon: require('@assets/flags/bis.png') },
  { code: 'kin', name: 'Kinyarwanda', icon: require('@assets/flags/kin.png') },
  { code: 'ood', name: 'O\'odham', icon: require('@assets/flags/ood.png') },
  { code: 'mah', name: 'Marshallese', icon: require('@assets/flags/mah.png') },
  { code: 'ewe', name: 'Ewe', icon: require('@assets/flags/ewe.png') },
  { code: 'nya', name: 'Chinyanja', icon: require('@assets/flags/nya.png') },
  { code: 'lkt', name: 'Lakota', icon: require('@assets/flags/lkt.png') },
  { code: 'roh', name: 'Romansh', icon: require('@assets/flags/roh.png') },
  { code: 'ton', name: 'Tongan', icon: require('@assets/flags/ton.png') },
  { code: 'aoz', name: 'Uab Meto', icon: require('@assets/flags/aoz.png') },
  { code: 'kek', name: 'Kekchi (Q\'eqchi\')', icon: require('@assets/flags/kek.png') },
  { code: 'cos', name: 'Corsican', icon: require('@assets/flags/cos.png') },
  { code: 'ava', name: 'Avar', icon: require('@assets/flags/ava.png') },
  { code: 'mwl', name: 'Mirandese', icon: require('@assets/flags/mwl.png') },
  { code: 'oar', name: 'Old Aramaic', icon: require('@assets/flags/oar.png') },
  { code: 'lou', name: 'Louisiana Creole', icon: require('@assets/flags/lou.png') },
  { code: 'izh', name: 'Ingrian', icon: require('@assets/flags/izh.png') },
  { code: 'non', name: 'Old Norse', icon: require('@assets/flags/non.png') },
  { code: 'osp', name: 'Old Spanish', icon: require('@assets/flags/osp.png') },
  { code: 'klj', name: 'Khalaj', icon: require('@assets/flags/klj.png') },
  { code: 'inh', name: 'Ingush', icon: require('@assets/flags/inh.png') },
  { code: 'dar', name: 'Dargwa', icon: require('@assets/flags/dar.png') },
  { code: 'ngt', name: 'Ngeq ', icon: require('@assets/flags/ngt.png') },
  { code: 'mic', name: 'Mi\'kmaq', icon: require('@assets/flags/mic.png') },
  { code: 'cjy', name: 'Jin Chinese', icon: require('@assets/flags/cjy.png') },
  { code: 'kaa', name: 'Karakalpak', icon: require('@assets/flags/kaa.png') },
  { code: 'new', name: 'Newari', icon: require('@assets/flags/new.png') },
  { code: 'jpa', name: 'Jewish Palestinian Aramaic', icon: require('@assets/flags/jpa.png') },
  { code: 'vro', name: 'Võro', icon: require('@assets/flags/vro.png') },
  { code: 'srd', name: 'Sardinian', icon: require('@assets/flags/srd.png') },
  { code: 'toi', name: 'Tonga (Zambezi)', icon: require('@assets/flags/toi.png') },
  { code: 'nan', name: 'Min Nan Chinese', icon: require('@assets/flags/nan.png') },
  { code: 'lez', name: 'Lezgi', icon: require('@assets/flags/lez.png') },
  { code: 'phn', name: 'Phoenician', icon: require('@assets/flags/phn.png') },
  { code: 'qxq', name: 'Qashqai', icon: require('@assets/flags/qxq.png') },
  { code: 'gil', name: 'Gilbertese', icon: require('@assets/flags/gil.png') },
  { code: 'nlv', name: 'Orizaba Nahuatl', icon: require('@assets/flags/nlv.png') },
  { code: 'tvl', name: 'Tuvaluan', icon: require('@assets/flags/tvl.png') },
  { code: 'lbe', name: 'Lak', icon: require('@assets/flags/lbe.png') },
  { code: 'vep', name: 'Veps', icon: require('@assets/flags/vep.png') },
  { code: 'bam', name: 'Bambara', icon: require('@assets/flags/bam.png') },
  { code: 'ofs', name: 'Old Frisian', icon: require('@assets/flags/ofs.png') },
  { code: 'alt', name: 'Southern Altai', icon: require('@assets/flags/alt.png') },
  { code: 'xqa', name: 'Karakhanid', icon: require('@assets/flags/xqa.png') },
  { code: 'tkl', name: 'Tokelauan', icon: require('@assets/flags/tkl.png') },
  { code: 'zea', name: 'Zeelandic', icon: require('@assets/flags/zea.png') },
  { code: 'emx', name: 'Erromintxela', icon: require('@assets/flags/emx.png') },
  { code: 'abq', name: 'Abaza', icon: require('@assets/flags/abq.png') },
  { code: 'brx', name: 'Bodo', icon: require('@assets/flags/brx.png') },
  { code: 'nau', name: 'Nauruan', icon: require('@assets/flags/nau.png') },
  { code: 'yua', name: 'Yucatec Maya', icon: require('@assets/flags/yua.png') },
  { code: 'laa', name: 'Southern Subanen', icon: require('@assets/flags/laa.png') },
  { code: 'szl', name: 'Silesian', icon: require('@assets/flags/szl.png') },
  { code: 'kam', name: 'Kamba', icon: require('@assets/flags/kam.png') },
  { code: 'mdf', name: 'Moksha', icon: require('@assets/flags/mdf.png') },
  { code: 'mnw', name: 'Mon', icon: require('@assets/flags/mnw.png') },
  { code: 'jdt', name: 'Juhuri (Judeo-Tat)', icon: require('@assets/flags/jdt.png') },
  { code: 'ajp', name: 'South Levantine Arabic', icon: require('@assets/flags/ajp.png') },
  { code: 'sag', name: 'Sango', icon: require('@assets/flags/sag.png') },
  { code: 'mai', name: 'Maithili', icon: require('@assets/flags/mai.png') },
  { code: 'chg', name: 'Chagatai', icon: require('@assets/flags/chg.png') },
  { code: 'otk', name: 'Old Turkish', icon: require('@assets/flags/otk.png') },
  { code: 'cpi', name: 'Chinese Pidgin English', icon: require('@assets/flags/cpi.png') },
  { code: 'mad', name: 'Madurese', icon: require('@assets/flags/mad.png') },
  { code: 'fuc', name: 'Pulaar', icon: require('@assets/flags/fuc.png') },
  { code: 'quc', name: 'K\'iche\'', icon: require('@assets/flags/quc.png') },
  { code: 'ban', name: 'Balinese', icon: require('@assets/flags/ban.png') },
  { code: 'aii', name: 'Assyrian Neo-Aramaic', icon: require('@assets/flags/aii.png') },
  { code: 'diq', name: 'Southern Zaza (Dimli)', icon: require('@assets/flags/diq.png') },
  { code: 'kiu', name: 'Northern Zaza (Kirmanjki)', icon: require('@assets/flags/kiu.png') },
  { code: 'snd', name: 'Sindhi', icon: require('@assets/flags/snd.png') },
  { code: 'mfe', name: 'Morisyen', icon: require('@assets/flags/mfe.png') },
  { code: 'bcl', name: 'Central Bikol', icon: require('@assets/flags/bcl.png') },
  { code: 'pal', name: 'Middle Persian (Pahlavi)', icon: require('@assets/flags/pal.png') },
  { code: 'tmw', name: 'Temuan', icon: require('@assets/flags/tmw.png') },
  { code: 'kxi', name: 'Keningau Murut', icon: require('@assets/flags/kxi.png') },
  { code: 'gom', name: 'Konkani (Goan)', icon: require('@assets/flags/gom.png') },
  { code: 'hsn', name: 'Xiang Chinese', icon: require('@assets/flags/hsn.png') },
  { code: 'hnj', name: 'Hmong Njua (Green)', icon: require('@assets/flags/hnj.png') },
  { code: 'crk', name: 'Plains Cree', icon: require('@assets/flags/crk.png') },
  { code: 'gaa', name: 'Ga', icon: require('@assets/flags/gaa.png') },
  { code: 'gan', name: 'Gan Chinese', icon: require('@assets/flags/gan.png') },
  { code: 'ayl', name: 'Libyan Arabic', icon: require('@assets/flags/ayl.png') },
  { code: 'mnr', name: 'Mono (USA)', icon: require('@assets/flags/mnr.png') },
  { code: 'syc', name: 'Syriac', icon: require('@assets/flags/syc.png') },
  { code: 'mni', name: 'Meitei', icon: require('@assets/flags/mni.png') },
  { code: 'tso', name: 'Tsonga', icon: require('@assets/flags/tso.png') },
  { code: 'osx', name: 'Old Saxon', icon: require('@assets/flags/osx.png') },
  { code: 'pfl', name: 'Palatine German', icon: require('@assets/flags/pfl.png') },
  { code: 'hdn', name: 'Northern Haida', icon: require('@assets/flags/hdn.png') },
  { code: 'lug', name: 'Luganda', icon: require('@assets/flags/lug.png') },
  { code: 'mnc', name: 'Manchu', icon: require('@assets/flags/mnc.png') },
  { code: 'aym', name: 'Aymara', icon: require('@assets/flags/aym.png') },
  { code: 'sot', name: 'Southern Sotho', icon: require('@assets/flags/sot.png') },
  { code: 'nys', name: 'Nyungar', icon: require('@assets/flags/nys.png') },
  { code: 'pli', name: 'Pali', icon: require('@assets/flags/pli.png') },
  { code: 'cyo', name: 'Cuyonon', icon: require('@assets/flags/cyo.png') },
  { code: 'rel', name: 'Rendille', icon: require('@assets/flags/rel.png') },
  { code: 'ssw', name: 'Swazi', icon: require('@assets/flags/ssw.png') },
  { code: 'hax', name: 'Southern Haida', icon: require('@assets/flags/hax.png') },
  { code: 'urh', name: 'Urhobo', icon: require('@assets/flags/urh.png') },
];
